name: Release Package

on:
  release:
    types:
      - published

jobs:
  package:
    name: Deploy release package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create release package branch
      run: |
        git branch -d package &> /dev/null || echo package branch not found
        git subtree split -P "$PKG_ROOT" -b package
        mv "Assets/Samples" /tmp/example
        git checkout package
        mkdir "Samples~"
        mv /tmp/example/* "Samples~/"
        git add "Samples~"
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git commit -am "Packaged project"
        git push -f -u origin package
      env:
        PKG_ROOT: "Packages/se.hertzole.settings-manager"
